workspace:
  base: /go
  path: src/github.com/YuukanOO/migrataur

pipeline:
  build:
    image: golang
    commands:
      - go get ./...
      - go build ./...
      - go vet ./...
      - go test ./... --cover -v